// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACubZTHR9PA5N0GQUefaTDn7JLFUSvaQU',
    appId: '1:585867154743:web:5c77aedb8e11d8cde436b2',
    messagingSenderId: '585867154743',
    projectId: 'shunya-defff',
    authDomain: 'shunya-defff.firebaseapp.com',
    storageBucket: 'shunya-defff.appspot.com',
    measurementId: 'G-QP2S6LQES9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDg5uoQNqquxNjHzHzIFpvvayIzn8b6Q',
    appId: '1:585867154743:android:6d1cb13bc7024d27e436b2',
    messagingSenderId: '585867154743',
    projectId: 'shunya-defff',
    storageBucket: 'shunya-defff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0S7tLuCqFxHHBr-TYv_CmyrsM_aBp61I',
    appId: '1:585867154743:ios:e5a7fed074e690dde436b2',
    messagingSenderId: '585867154743',
    projectId: 'shunya-defff',
    storageBucket: 'shunya-defff.appspot.com',
    iosBundleId: 'com.harchani.asmitaFlutter',
  );

}